# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "CK-CARE Team Meeting"                                # Your name
  description: "This is the Website specifically dedicated to CK-CARE Team Meeting"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  page-footer:
    right: "Augsburg, Feb 24-25th, 2025"
    left: "CK-CARE"
   
    
  
  
